### ISSUE TITLE
last day of the month

### ISSUE THREAD

**Issue by rurounijones** [mojombo/chronic#26]
I am trying to find a way of getting the last day of a month, for example: last day of last month

I have tried various combos but cannot find anything. I have had a look through the code and it is a bit beyond me. Does anyone know if this can be done?

I should mention that the first day works. Something like "last month first day" or "first day of last month" is fine.

**Comment by timfong888** [comment]
+1 last day of the month

**Comment by kovpack** [comment]
+1 last day of the month

**Comment by shrav** [comment]
+1 last day of the month

**Comment by zedtux** [comment]
+1

**Comment by zedtux** [comment]
Here is how I did it based on @jeremywadsack's comment:

```ruby
Chronic.parse('1st day next month') - 1.day
```

**Comment by SRajapakseOscar** [comment]
This is a much needed feature... any ETA?
