### ISSUE TITLE
undefined method `time_class=' for Chronic:Module

### ISSUE THREAD

**Issue by angelacode** [mojombo/chronic#302]
I have the following code:

    Time.zone = "America/Los_Angeles"
      Chronic.time_class = Time.zone

But I get an error of undefined method `time_class=' for Chronic:Module

This seems to have worked before so not sure what is causing the problem

**Comment by davispuh** [comment]
It must be some conflict/monkey-patching by some other gem as there haven't been any changes to Chronic for a while and it works fine for me. Look into what gems and versions are loaded to find cause.

**Comment by angelacode** [comment]
You are right!  I was using the tickle gem (any thought if chronic will incorporate similar functionality?  tickle allows recurring events) and it required a really old version of chronic and bundle installed that dependency.
