### ISSUE TITLE
Parsing 'next friday' for the first of November returns a Saturday

### ISSUE THREAD

**Issue by MrLeebo** [mojombo/chronic#318]
```
Chronic.parse('next friday', now: Date.new(2015, 11)).to_date
=> Sat, 07 Nov 2015
```

I expected `Fri, 06 Nov 2015`. Am I missing something?

**Comment by andrewhavens** [comment]
Sounds like a timezone issue. When setting `now` you didn't specify a time zone, so I think it defaults to UTC.
