### ISSUE TITLE
1st day of this month bug?

### ISSUE THREAD

**Issue by brianstarke** [mojombo/chronic#32]
Seeing an issue when trying to get the first day of the current month, am I just not writing this correctly?  First day of last month and next month seem to work fine.  

eg:

ruby-1.9.2-p0 > Chronic.parse '1st day of last month'
=> 2010-12-01 12:00:00 -0500 
ruby-1.9.2-p0 > Chronic.parse '1st day of next month'
=> 2011-02-01 12:00:00 -0500 
ruby-1.9.2-p0 > Chronic.parse '1st day of this month'
=> 2011-01-11 12:00:00 -0500

**Comment by sesam** [comment]
Chronic.parse("1st DATE of this month", :guess => false) # works
Chronic.parse("1st day of this month", :guess => false) # returns today (why???)

**Comment by davispuh** [comment]
looks like a bug :P
