### ISSUE TITLE
Chronic.parse("today 11:00am") returns nil on 2011-11-06

### ISSUE THREAD

**Issue by madeofstars0** [mojombo/chronic#74]
I have been having issues around daylight savings time changes with Chronic calls.  Last sunday I was having issues with Chronic returning nil, but I didn't capture any way to reproduce the error.  I had problems with Chronic again today, here is what I was noticing in my Rails 3.0.10 app (MRI ruby 1.9.2 and 1.9.3)

```
Time.zone = "Central Time (US & Canada)"
Chronic.time_class = Time.zone
Chronic.parse("today 11:00am") # => nil
Chronic.parse("today 10:59am") # => Sun, 06 Nov 2011 10:59:00 CST -06:00
Chronic.parse("today 11:59am") # => nil
Chronic.parse("today 12:00pm") # => Sun, 06 Nov 2011 12:00:00 CST -06:00 
```

I was trying to reproduce Chronic returning me nil on 10-30 using Timecop, but was unable to reproduce the errors, so I don't know if you will be able to use something like Timecop to validate this issue after today.

I also did this little test in irb (ruby 1.9.3)

```
require 'chronic'
Chronic.parse("today 11:00am") # => nil
```

My servers (ruby 1.9.2) are running with the timezone set to GMT at the OS level, the development machines (1.9.2 and 1.9.3) are set to Central Time at the OS level.

**Comment by mikeraimondi** [comment]
I can confirm that this issue still exists. `Chronic.parse('12:00')` returns `nil` on March 8, 2015.

**Comment by davispuh** [comment]
that's because of DST, currently no support for it, there's loads of such issues #147, #177, #179, #222, #228, #282 
they all will be probably fixed once DST is properly implemented.

**Comment by simonmorley** [comment]
+1
